import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

/**
 * Sitemap integrity tests.
 *
 * Reads public/sitemap.xml (generated by scripts/generate-sitemap.js)
 * and asserts the structural invariants Google Search Console will enforce.
 *
 * If sitemap.xml is missing or malformed at this point, ALL of CI is broken.
 */

const SITEMAP_PATH = resolve(process.cwd(), 'public/sitemap.xml');
const EXPECTED_HOST = 'https://www.perfect1.co.il';

let xml;
let urls;

beforeAll(() => {
  if (!existsSync(SITEMAP_PATH)) {
    throw new Error(
      `public/sitemap.xml not found. Run "node scripts/generate-sitemap.js" first.`
    );
  }
  xml = readFileSync(SITEMAP_PATH, 'utf-8');
  urls = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1]);
});

describe('sitemap integrity', () => {
  it('starts with the XML declaration as the very first bytes (no BOM, no preceding comment)', () => {
    expect(xml.startsWith('<?xml')).toBe(true);
  });

  it('declares the sitemaps.org urlset namespace', () => {
    expect(xml).toMatch(/<urlset[^>]+xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9"/);
  });

  it('contains at least 50 URLs (sanity floor)', () => {
    expect(urls.length).toBeGreaterThanOrEqual(50);
  });

  it('every URL uses https://www.perfect1.co.il (no http, no apex, no other host)', () => {
    const offenders = urls.filter((u) => !u.startsWith(EXPECTED_HOST));
    expect(offenders, `non-canonical URLs found: ${offenders.join(', ')}`).toEqual([]);
  });

  it('no duplicate URLs', () => {
    const seen = new Map();
    const dupes = [];
    for (const u of urls) {
      const n = (seen.get(u) || 0) + 1;
      seen.set(u, n);
      if (n === 2) dupes.push(u);
    }
    expect(dupes, `duplicates: ${dupes.join(', ')}`).toEqual([]);
  });

  it('every URL is well-formed (no spaces, no trailing slashes except homepage, no query strings)', () => {
    const bad = urls.filter((u) => {
      if (/\s/.test(u)) return true;
      if (u.includes('?')) return true;
      if (u.includes('#')) return true;
      // Trailing slash allowed only for homepage
      if (u !== EXPECTED_HOST + '/' && u.endsWith('/')) return true;
      return false;
    });
    expect(bad, `malformed URLs: ${bad.join(', ')}`).toEqual([]);
  });

  it('every <url> entry has lastmod, changefreq, priority', () => {
    const entries = xml.match(/<url>[\s\S]*?<\/url>/g) || [];
    for (const e of entries) {
      expect(e).toMatch(/<loc>/);
      expect(e).toMatch(/<lastmod>\d{4}-\d{2}-\d{2}<\/lastmod>/);
      expect(e).toMatch(/<changefreq>(daily|weekly|monthly|yearly)<\/changefreq>/);
      expect(e).toMatch(/<priority>(0\.\d|1\.0)<\/priority>/);
    }
  });

  it('homepage is listed', () => {
    expect(urls).toContain(EXPECTED_HOST + '/');
  });

  it('the sitemap closes with </urlset>', () => {
    expect(xml.trimEnd().endsWith('</urlset>')).toBe(true);
  });
});
